name: tst

env:
  APPLE_CONTAINER_VERSION: 0.4.1
  
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-api:
    name: run-test-commands
    runs-on: macos-26
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: fetch apple container
        run: wget https://github.com/apple/container/releases/download/${APPLE_CONTAINER_VERSION}/container-${APPLE_CONTAINER_VERSION}-installer-signed.pkg

      - name: install apple container
        run: sudo installer -pkg container-${APPLE_CONTAINER_VERSION}-installer-signed.pkg -target / -verbose

      - name: setup tmate
        run: |
          brew install tmate

      - name: Start internal tmate session and start container system using this tmate session
        run: |
          # Start a detached tmate session
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          # skip welcome screen
          tmate -F -S /tmp/tmate.sock send-keys "q" C-m

          # Send Apple Container commands automatically
          tmate -S /tmp/tmate.sock send-keys "echo 'Starting Apple Container...'" C-m
          tmate -S /tmp/tmate.sock send-keys "sudo container system start --enable-kernel-install | tee /tmp/container.log" C-m
          
          # Loop until 'container system status' returns exit code 1 or timeout (60s)
          START=$SECONDS
          TIMEOUT=60

          while [ $((SECONDS - START)) -lt $TIMEOUT ]; do
            # Capture tmate session output
            tmate -S /tmp/tmate.sock capture-pane -p > /tmp/container.log
            cat /tmp/container.log

            # Check container status locally
            if sudo container system status >/dev/null 2>&1; then
              # Exit code 0 → container is ready
              echo "Container is ready. Exiting loop."
              break
            else
              echo "Container not ready yet..."
            fi
          done

          # stop tmate session
          tmate -S /tmp/tmate.sock kill-session
          tmate kill-server

      - name: check container root
        run: |
          sudo container image pull hello-world
          sudo container images ls
        
      - name: install docker cli
        run: |
          brew install docker

      - name: install socktainer
        run: |
          wget https://github.com/socktainer/socktainer/releases/download/v0.2.0/socktainer
          chmod 755 socktainer

      - name: run socktainer
        run: |
          nohup sudo ./socktainer > service.log 2>&1 &
          echo $! > service.pid

      - name: check docker image with socktainer
        run: |
          DOCKER_HOST=unix://$HOME/.socktainer/container.sock docker image ls

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
