name: tst

env:
  APPLE_CONTAINER_VERSION: 0.4.1
  
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-api:
    name: run-test-commands
    runs-on: macos-26
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: fetch apple container
        run: wget https://github.com/apple/container/releases/download/${APPLE_CONTAINER_VERSION}/container-${APPLE_CONTAINER_VERSION}-installer-signed.pkg

      - name: install apple container
        run: sudo installer -pkg container-${APPLE_CONTAINER_VERSION}-installer-signed.pkg -target /

      - name: start apple container
        run: sudo container system start --disable-kernel-install

      - name: download kernel
        run: wget https://github.com/kata-containers/kata-containers/releases/download/3.17.0/kata-static-3.17.0-arm64.tar.xz

      - name: set kernel
        run: container system kernel set --binary kata-static-3.17.0-arm64.tar.xz
        

      - name: install docker cli
        run: |
          brew install docker

      - name: install socktainer
        run: |
          wget https://github.com/socktainer/socktainer/releases/download/v0.2.0/socktainer
          chmod 755 socktainer

      - name: run socktainer
        run: |
          nohup ./socktainer > service.log 2>&1 &
          echo $! > service.pid

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
